# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to EEG analysis
author: Alexander Enge
logo: misc/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: intro-to-eeg.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - misc/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/alexenge/intro-to-eeg
  path_to_book: .
  branch: main

launch_buttons:
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: misc/favicon.png
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - sphinxcontrib.apa
  config:
    bibtex_reference_style: apastyle
    bibtex_default_style: apa
    # nb_custom_formats:
    #   .py:
    #     - jupytext.reads
    #     - fmt: py:percent
    nb_merge_streams: true
